### ISSUE TITLE
Przyklejanie wyrazów do poprzedniego

### ISSUE THREAD

**Issue by nillgk** [iworks/sierotki#2]
Przydałoby się działanie odwrotne do sierotek przenoszonych do nowego wiersza - czyli przyklejanie wyrazu do poprzedniego np. dla "się", żeby wyrażenia typu "mylisz się", "weź się" (w garść), "przysuń się",... były zawsze pokazywane łącznie.

**Comment by iworks** [comment]
Przykro mi, ale nie ma takiej zasady gramatycznej w języku polskim, więc nie będzie takiej funkcjonalności.

**Comment by nillgk** [comment]
Dziękuję za odpowiedź.

Z "się" to był przykład - chodziło mi o samą funkcjonalność przyklejania także do poprzedniego wyrazu z możliwością dodawania/wykluczania słów przez administratora strony.

Pozdrawiam
Grzegorz

**Comment by iworks** [comment]
@nillgk - nadal - nie znam takiej reguły gramatycznej - czy możesz mi wskazać?

**Comment by nillgk** [comment]
Dla takiej funkcji wg mnie nie musi być reguł - za powód może wystarczyć osobiste przekonanie autora danej strony ;)
Inne przypadki, gdzie przydaje się trzymanie wyrazów razem z poprzednim to rok, wiek, waluta,... - np.: "1945 r.", "XX w.", "100 €", "500 zł"

**Comment by iworks** [comment]
@nillgk rozumiem argument, ale nie widzę tego w mojej wtyczce. Zawsze możesz albo sforkować, albo utworzyć rozszerzenie do wtyczki. 

Jeżeli zabraknie gdzieś filtra - wrzuć PR i będzie.

**Comment by nillgk** [comment]
Nie znam się na tym niestety... Możesz mi polecić jakieś miejsce w sieci do zdalnego nauczenia się tworzenia takich modyfikacji?

**Comment by nillgk** [comment]
To ostatnie pytanie o to - jaki to język programowania, w którym mogę modyfikować Twój plugin? ;)

**Comment by iworks** [comment]
> To ostatnie pytanie o to - jaki to język programowania, w którym mogę modyfikować Twój plugin? ;)

PHP
