### ISSUE TITLE
Missing custom post type in configuration

### ISSUE THREAD

**Issue by iworks** [iworks/sierotki#5]
There is no ability to turn replacement in custom post type.

Original:

https://wordpress.org/support/topic/sierotki-cpt/

Sierotki + CPT

Cześć Marcinie,
z jakiegoś powodu Sierotki przestały działać w przypadku własnych typów wpisu. Zerknąłbyś proszę?

**Comment by flexcodenet** [comment]
A ja myślałem, że framework, który używam coś nie tak rejestruje CPT i stąd problem, bo jak użyłem filtra:

orphans_indicator_options_use_cache aby był ustawiony na false, to problem znikał :) 

Dzięki za fix

**Comment by flexcodenet** [comment]
Lekcja dla mnie aby nie zakładać czegoś od razu :) Sporo czasu zmarnowałem na debug problemu. Miałem w sumie zgłosić problem, ale zakładałem, że nie jest to możliwe aby Marcin coś miał nie tak 😂
